export const APP_CONSTANTS = {
  BOT_NAME: 'Fredrik',
  VERSION: '1.0.0',
  DEFAULT_PREFIX: '.',
  SUPPORTED_MODES: ['public', 'private', 'group', 'inbox'] as const,
  EMOJIS: {
    BOT: '🤖',
    SUCCESS: '✅',
    ERROR: '❌',
    WARNING: '⚠️',
    INFO: 'ℹ️',
    LOADING: '⏳',
    STICKER: '🏷️',
    MEDIA: '🎬',
    AUDIO: '🎵',
    AI: '🧠',
    ADMIN: '🛡️',
    OWNER: '👑',
    LOCK: '🔒',
    CALL: '📞',
    REMINDER: '⏰',
    STATS: '📊',
    PING: '🏓',
  },
  COOLDOWNS: {
    DEFAULT_COMMAND_SECONDS: 3,
    AI_COMMAND_SECONDS: 5,
    MEDIA_COMMAND_SECONDS: 6,
    STICKER_SECONDS: 4,
    BROADCAST_SECONDS: 15,
  },
  RATE_LIMITS: {
    MAX_MESSAGES_PER_MINUTE: 30,
    BAN_DURATION_MINUTES: 5,
  },
  EXIF: {
    PACK: 'Fredrik',
    AUTHOR: 'Fredrik Multi-Device Bot',
  },
};
